version: '3.8'

services:

  redis:
    image: redis:7-alpine
    container_name: avalanches-redis
    environment:
      REDIS_PASSWORD: redis_password
    command: ["redis-server", "--requirepass", "redis_password"]
    ports:
      - "6379:6379"
    networks:
      - avalanches-network

  app:
    build:
      context: .
    container_name: avalanches-app
    environment:
      LOG_LEVEL: DEBUG
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis_password
      PAGAMENTO_WEBHOOK_HOST: pagamento-mock-service
      PAGAMENTO_WEBHOOK_PORT: 5001
      PAGAMENTO_WEBHOOK_ENDPOINT: pagamento
    ports:
      - "8082:8082"
    depends_on:
      - redis
    networks:
      - avalanches-network


  pagamento-mock-service:
    build:
      context: ./mock/application-avalanches-pagamento-externo-ms
    container_name: pagamento-mock-service
    ports:
      - "5001:5001"
    networks:
      - avalanches-network

networks:
  avalanches-network:
