version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: avalanches-postgres
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: avalanches_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - avalanches-network

  redis:
    image: redis:7-alpine
    container_name: avalanches-redis
    environment:
      REDIS_PASSWORD: redis_password
    command: ["redis-server", "--requirepass", "redis_password"]
    ports:
      - "6379:6379"
    networks:
      - avalanches-network

  app:
    build:
      context: .
    container_name: avalanches-app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: avalanches_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis_password
    ports:
      - "8282:8282"
    depends_on:
      - postgres
      - redis
    networks:
      - avalanches-network

volumes:
  postgres-data:

networks:
  avalanches-network:
