apiVersion: v1
kind: Service
metadata:
  name: pedido-app-loadbalancer
  labels:
    app: pedido
spec:
  type: LoadBalancer
  ports:
    - port: 82         # Porta externa
      targetPort: 8082    # Porta onde sua aplicação está rodando
  selector:
    app: pedido
