apiVersion: v1
kind: Service
metadata:
  name: pagamento-service
spec:
  selector:
    app: pagamento
  ports:
    - port: 8082     # Porta que o Ingress está usando para o tráfego externo
      targetPort: 8082  # Porta onde a aplicação está ouvindo no container
      protocol: TCP
  type: NodePort