apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagamento-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pagamento
  template:
    metadata:
      labels:
        app: pagamento
    spec:
      containers:
        - name: pagamento
          image: 307946636040.dkr.ecr.sa-east-1.amazonaws.com/ms-pagamento:latest
          ports:
            - containerPort: 8082
          resources:
            requests:
              cpu: "300m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
          env:
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: pagamento-dbcredentials
                  key: redis_host
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: pagamento-dbcredentials
                  key: redis_port
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pagamento-dbcredentials
                  key: redis_password
            - name: PAGAMENTO_WEBHOOK_HOST
              value: "k8s-default-ingressa-0faf251d7e-890170821.sa-east-1.elb.amazonaws.com" 
            - name: PAGAMENTO_WEBHOOK_PORT
              value: "5001"     
            - name: PAGAMENTO_WEBHOOK_ENDPOINT
              value: "pagamento" 
