name: Build Application

# Dispara o workflow em todos os commits em qualquer branch
on:
  push:
    branches:
      - '**' # Para todas as branches
  pull_request: # Também em pull requests
    branches:
      - '**'

jobs:
  build:
    name: Build with Maven
    runs-on: ubuntu-latest # Sistema operacional do runner

    steps:
      # Passo 1: Checa o código do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configura o JDK necessário
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21 # Versão do JDK
          distribution: temurin # Distribuição do JDK (Eclipse Temurin)

      # Passo 3: Configura o cache para dependências Maven
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository # Caminho do cache do Maven
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }} # Identificador do cache
          restore-keys: |
            ${{ runner.os }}-maven-

      # Passo 4: Executa o build com Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Passo 5: (Opcional) Testa o build final (se você quiser adicionar testes)
      - name: Run Tests
        run: mvn test
